language: "perl"
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10.1"
before_install:
    - cd Robot
install:
    - cpanm -v --installdeps --notest .

script: "perl Makefile.PL && make && make test"
